---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fdo
    fdo-service: manufacturing
  name: manufacturing-server-svc
spec:
  ports:
    # - name: "9001"
    #   nodePort: 30077
    #   port: 9001
    #   targetPort: 9001
    - protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: fdo
    fdo-service: manufacturing
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manufacturing-server-ingress
  labels:
    app: fdo
    fdo-service: manufacturing
spec:
  ingressClassName: nginx
  rules:
    - host: manufacturing-192.168.122.70.sslip.io
    - http:
        paths:
          - backend:
              service:
                name: manufacturing-server
                port:
                  number: 9001
            path: /
            pathType: Prefix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manufacturing-server
  labels:
    app: fdo
    fdo-service: manufacturing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdo
      fdo-service: manufacturing
  template:
    metadata:
      annotations:
        # bind-mount-options: /root/fdo/config:Z
      labels:
        app: fdo
        fdo-service: manufacturing
      name: manufacturing-server
    spec:
      containers:
        - image: quay.io/fido-fdo/manufacturing-server:latest
          name: manufacturing-server
          ports:
            - containerPort: 9001
              hostPort: 9001
          volumeMounts:
            - mountPath: /etc/fdo/manufacturing-server.conf.d/
              name: manufacturing-server-config
              readOnly: true
            - mountPath: /etc/fdo/sessions
              name: sessions
            - mountPath: /etc/fdo/ownership_vouchers
              name: ownership-vouchers
            - mountPath: /etc/fdo/keys/
              name: keys
              readOnly: true
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop: ["ALL"]
          # command: ["ls", "-l", "/etc/fdo/keys"]
      volumes:
        - name: manufacturing-server-config
          configMap:
            name: manufacturing-server-config
        - name: sessions
          emptyDir: {}
        - name: ownership-vouchers
          emptyDir: {}
          # persistentVolumeClaim:
          #   claimName: fdo-ownership-vouchers-pvc
        - name: keys
          # alternatively to this the secrets could be put into a single secret with multiple files/keys
          # see https://stackoverflow.com/questions/59079318/how-to-mount-multiple-files-secrets-into-common-directory-in-kubernetes
          # or use multiple secrets mounted to the same directory:
          # https://github.com/fdo-rs/fdo-operator/blob/main/controllers/fdomanufacturingserver_controller.go#L157-L160
          # (https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#mounting-the-same-persistentvolume-in-two-places)
          projected:
            sources:
              - secret:
                  name: device-ca-cert-pem
              - secret:
                  name: device-ca-key-der
              - secret:
                  name: diun-cert-pem
              - secret:
                  name: diun-key-der
              - secret:
                  name: manufacturer-cert-pem
              - secret:
                  name: manufacturer-key-der
              - secret:
                  name: owner-cert-pem
              - secret:
                  name: owner-key-der
      # securityContext:
      #   runAsNonRoot: true
      #   seccompProfile:
      #     type: RuntimeDefault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manufacturing-server-config
  labels:
    app: fdo
    fdo-service: manufacturing
data:
  manufacturing-server.yml: |+
    ---
    session_store_driver:
      Directory:
        path: /etc/fdo/sessions
    ownership_voucher_store_driver:
      Directory:
        path: /etc/fdo/ownership_vouchers
    public_key_store_driver:
      Directory:
        path: /etc/fdo/keys
    bind: 0.0.0.0:9001
    rendezvous_info:
    - dns: fdo.example.com
      device_port: 8082
      owner_port: 8082
      protocol: http
    - ip: 127.0.0.1
      device_port: 8084
      owner_port: 8084
      protocol: http
    protocols:
      diun:
        key_path: /etc/fdo/keys/diun_key.der
        cert_path: /etc/fdo/keys/diun_cert.pem
        key_type: SECP256R1
        mfg_string_type: SerialNumber
        allowed_key_storage_types:
        - FileSystem
    manufacturing:
      manufacturer_cert_path: /etc/fdo/keys/manufacturer_cert.pem
      manufacturer_private_key: /etc/fdo/keys/manufacturer_key.der
      owner_cert_path: /etc/fdo/keys/owner_cert.pem
      device_cert_ca_private_key: /etc/fdo/keys/device_ca_key.der
      device_cert_ca_chain: /etc/fdo/keys/device_ca_cert.pem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fdo-pv-volume
  labels:
    type: local
spec:
  # storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/fdo/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fdo-ownership-vouchers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

