---
session_store_driver:
  Directory:
    path: /etc/fdo/sessions
ownership_voucher_store_driver:
  Directory:
    path: /etc/fdo/owner_vouchers
public_key_store_driver:
  Directory:
    path: /etc/fdo/keys
bind: 0.0.0.0:9001
rendezvous_info:
- dns: fdo.example.com
  device_port: 8082
  owner_port: 8082
  protocol: http
- ip: 127.0.0.1
  device_port: 8084
  owner_port: 8084
  protocol: http
protocols:
  diun:
    key_path: /etc/fdo/allkeys/diun_key.der
    cert_path: /etc/fdo/allkeys/diun_cert.pem
    key_type: SECP256R1
    mfg_string_type: SerialNumber
    allowed_key_storage_types:
    - FileSystem
manufacturing:
  manufacturer_cert_path: /etc/fdo/allkeys/manufacturer_cert.pem
  manufacturer_private_key: /etc/fdo/allkeys/manufacturer_key.der
  owner_cert_path: /etc/fdo/allkeys/owner_cert.pem
  device_cert_ca_private_key: /etc/fdo/allkeys/device_ca_key.der
  device_cert_ca_chain: /etc/fdo/allkeys/device_ca_cert.pem

